name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - develop

permissions:
  contents: write

# Fixes the Node 20 warning by forcing the virtual runner to load JavaScript actions via Node 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Application
        run: npx ng build --configuration=production --base-href="https://rahul-shaw18.github.io/Flight-Tracking/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/Flight-Tracking/browser
          branch: gh-pages